spring:
  application:
    name: msnotify
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      uri: mongodb://localhost:27017/notify

mq:
  queues:
    listener-rabbitmq: listener-rabbitmq

server:
  port: 8081