version: '3.9'

services:
  msuser:
    image: msuserimg
    restart: always
    build:
      context: ./msuser
      dockerfile: Dockerfile
    container_name: msuser
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqlimg:3306/msuser?createDatabaseIfNotExist=true&serverTimezone=UTC&autoReconnect=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - JWT_SECRET_KEY=secrets
      - JWT_EXPIRATION=3600000
      - SPRING_RABBITMQ_HOST=rabbitmqimg
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      - mysqlimg
      - rabbitmqimg
    networks:
      - app-network

  msnotify:
    image: msnotifyimg
    restart: always
    build:
      context: ./msnotify
      dockerfile: Dockerfile
    container_name: msnotify
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongoimg:27017/msnotify
      - SPRING_RABBITMQ_HOST=rabbitmqimg
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      - mongoimg
      - rabbitmqimg
      - msuser
    networks:
      - app-network

  mongoimg:
    image: mongo:5.0
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: msnotify
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  mysqlimg:
    image: mysql:8.0
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: msuser
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  rabbitmqimg:
    image: rabbitmq:4.0-management
    restart: always
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

volumes:
  db_data:
  mongo_data:

networks:
  app-network:
    driver: bridge
