spring:
  application:
    name: msnotify
  rabbitmq:
    host: rabbitmqimg
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      uri: mongodb://mongoimg:27017/msnotify

mq:
  queues:
    listener-rabbitmq: listener-rabbitmq

server:
  port: 8081