spring:
  application:
    name: msnotify
  rabbitmq:
    queue: listener
    addresses: amqps://uzgvrvob:zH6m8uSarkXR4PMem9NfPbx-6Hhw84TJ@shrimp.rmq.cloudamqp.com/uzgvrvob
  data:
    mongodb:
      uri: mongodb://mongoimg:27017/msnotify

server:
  port: 8081