spring:
  application:
    name: msuser
  rabbitmq:
    host: rabbitmqimg
    port: 5672
    username: guest
    password: guest
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysqlimg:3306/msuser?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show_sql: false

logging:
  level:
    org.springframework.amqp: DEBUG
    com.rabbitmq.client: DEBUG

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
  packagesToScan: com.compass.msuser.web.controller

mq:
  queues:
    listener-rabbitmq: listener-rabbitmq

security:
  jwt:
    token:
      secret-key: secrets
      expire-length: 3600000