spring:
  application:
    name: msclientes

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://server:password@localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/log-file.log